apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: transmission
data:
  LOCAL_NETWORK: 192.168.1.0/24
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "4"
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "10000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "100"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  WEBPROXY_ENABLED: "false"



